spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: "mySecretKey12345mySecretKey12345mySecretKey12345"  # tối thiểu 32 ký tự
  expiration: 86400000  # 24 giờ tính bằng millisecond

server:
  port: 8080
